version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: testable

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - 5000:5000

    env_file:
      - .env
      - docker.env

    entrypoint:
      - "/docker-entrypoint.sh"
      - "/usr/local/bin/uvicorn"
      - "src.runner:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "5000"
      - "--timeout-keep-alive 90"

    volumes:
      - ./src:/src-volume/src
      - ./tests:/src-volume/tests

  postgres:
    image: postgres:11.16-alpine3.16
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${DATABASE_NAME}"]
      interval: 2s
      retries: 10
      start_period: 5s
      timeout: 10s

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ayomi

    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "pg-dev-data:/var/lib/postgresql/data"


volumes:
  pg-dev-data:
  cache-dev-data:
