version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: testable
      args:
        INCLUDE_TEST_REQUIREMENTS: "1"

    depends_on:
      postgres:
        condition: service_healthy

    expose:
      - 5000

    env_file:
      - .env
      - docker.env

    environment:
      DATABASE_NAME: "ayomi_test"

    volumes:
      - ./src:/src-volume/src
      - ./tests:/src-volume/tests


  postgres:
    image: postgres:11.16-alpine3.16
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${DATABASE_NAME}"]
      interval: 2s
      retries: 10
      start_period: 5s
      timeout: 10s

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ayomi_test

    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
